baseurl = "https://people-unleashed.com/"
title = "PEOPLE Unleashed"
paginate = 5
buildFuture = true
theme = "story"

[params]
  author = "PEOPLE Unleashed"
  twitter = "https://people-unleashed.com/"
  classes = []

[[menu.main]]
  name = "Talks"
  title = "Talks"
  url = "/talks/"

[[menu.main]]
  name = "Slides"
  title = "Slides"
  url = "/slides/"

[[menu.main]]
  name = "Archives"
  title = "Archives"
  url = "/archives/"



[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]


